<!DOCTYPE html>
<html lang="pt-BR">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Oops...</title>

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="/assets/css/404.css" />
</head>

<body>
	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Erro</h1>
				<h2>404 - Página não encontrada</h2>
			</div>
			<a href="/">Voltar</a>
		</div>
	</div>
</body>
</html>
